### ISSUE TITLE
ajouter les scopes aux consumers

### ISSUE THREAD

**Issue by pknoth** [betagouv/api-particulier-admin#4]
- [x] Ajouter l'attribut scopes au modèle Token, un array pouvant contenir les scopes utilisateur de api-particulier en l'occurence "dgfip" et/ou "caf".

- [x] Créer les vues associées (affichage + formulaire)

- [ ] Créer une migration ajoutant le scope "dgfip" à tous les Tokens

NB: l'intitulé du scope est toujours en cours de définition

**Comment by annemarie35** [comment]
Cf https://github.com/betagouv/api-particulier/issues/51
